observeinc/terraform-aws-collection

- README.md
- lambda.tf
- s3.tf
- variables.tf
We update the default actions list implicitly every time we bump the
version of the `terraform-aws-lambda` module. Rather than keep tabs on
what actions are supported in two separate modules, always fall back to
whatever the underlying lambda module supports.
In practice this change breaks backward compatibility, but there is no
loss of functionality. The `snapshot_include` and `snapshot_exclude`
variables can be used to tailor the list of actions if needed.
> fix: remove action variable, allow falling back to default

- README.md
- versions.tf
> fix: pin AWS provider to v3.X

- README.md
- firehose.tf
- lambda.tf
- subscription.tf
- variables.tf
This change replaces the old cloudwatch logs subscription with the new stuff in https://github.com/observeinc/terraform-aws-cloudwatch-logs-subscription.
This exposes a few new variables and removes the subscribe-to-lambda variable.
Testing: Successfully applied in Thunderdome.
> feat: use new log group subscription module

- README.md
- eventbridge.tf
- firehose.tf
- lambda.tf
- s3.tf
- variables.tf
BREAKING CHANGE: `observe_token` must now be in
`{datastream_token_id}:{datastream_token_secret}` format.
> feat!: bump lambda, kinesis-firehose modules

- README.md
- firehose.tf
- lambda.tf
- main.tf
- subscription.tf
- variables.tf
BREAKING CHANGE:
`subscribed_log_group_names`, `cloudwatch_logs_subscribe_to_lambda` and
`cloudwatch_logs_subscribe_to_lambda` are no longer available as input
variables. Use `subscribed_log_group_matches` and
`subscribed_log_group_excludes` instead
> fix!: remove deprecated variables

- README.md
- subscription.tf
This closes https://github.com/observeinc/terraform-aws-collection/issues/32 by passing the tags field into a new version of the subscription module.
I have tested by applying the terraform-aws-collection module and inspecting the tags.
> fix: pass tags into subscription submodule

- README.md
- subscription.tf
- variables.tf
This fixes an issue where one could not install multiple terraform-aws-collection modules in the same region.
I tested by installing terraform-aws-collection in Thunderdome.
> fix: pass name into observe_cloudwatch_logs_subscription

- .github/dependabot.yml
Enables dependency update PRs for Terraform (providers/modules) and GitHub Actions. 
Important functionality is handled by child modules, with fixed versions:
https://github.com/observeinc/terraform-aws-collection/blob/78a6420b8a60ddca095444d7c778afcd00d3d29e/lambda.tf#L3
Arguably these should be ranges that allow patch updates. But even then, Dependabot is still useful for ensuring these ranges are bumped on new minors.
> chore: add dependabot for Terraform and Actions

- README.md
- versions.tf
Replaces the [legacy `required_providers` declaration](https://developer.hashicorp.com/terraform/language/providers/requirements#v0-12-compatible-provider-requirements) with `{source, version}`.
Fixes warnings about implicit provider selection when passing in a provider instance to the module. Closes #31.
Since Terraform continues to support this syntax for backward compatibility with 0.12, we need to enforce this separately. https://github.com/terraform-linters/tflint-ruleset-terraform/pull/64 will allow us to detect and reject this syntax in the future.
I tried to write a test module but was unable to reproduce the originally reported warning on `terraform validate`:
```tf
module "m" {
source = "../"
observe_token = "id:secret"
observe_customer = "12345"
providers = {
aws = aws.aliased …
```
> fix: set `source` in `required_providers`

- README.md
- subscription.tf
- versions.tf
This commit bumps the cloudwatch logs subscription module and gates it conditionally on the `subscribed_log_group_matches` and `subscribed_log_group_excludes` variables. If neither list is provided, the module will not be installed.
To retain the implicit behavior from 1.X versions, users can explicitly provide log groups, e.g:
```
module "observe_collection" {
source           = "observeinc/collection/aws"
name             = var.name
observe_customer = "<customer_id>"
observe_token    = "<secret>"
subscribed_log_group_matches = [
"/aws/lambda/${var.name}",
"/aws/firehose/${var.name}",
]
}
```
As a result of these changes, the minimum terraform provider version is now 1.1.0. This is matches the requirements of the underyling cloudwatch logs subscription module, and allows the usage of …
> fix!: update cloudwatch logs subscription module

- README.md
- eventbridge.tf
- firehose.tf
- variables.tf
This commit changes the set of default patterns we use for forwarding Eventbridge events to Observe. This set can be overridden through the `eventbridge_patterns` variable.
Our default rule set now contains two rules:
- a rule that matches all events _other_ than Cloudtrail
- a rule that matches all Cloudtrail excluding management events in the `cloudtrail_exclude_management_event_sources` list.
> feat: allow overriding eventbridge rules

- README.md
- s3.tf
- variables.tf
This commit allows users to provide their own s3_bucket definition. This gives users the opportunity to provide whatever bucket is compliant with local policies, rather than forcing us to surface all possible configuration for bucket.
> feat: allow overriding `s3_bucket`

- README.md
- s3.tf
Recent changes to bucket settings flipped defaults (https://docs.aws.amazon.com/AmazonS3/latest/userguide/create-bucket-faq.html)
This change incompatible with our existing use of canned ACLs.  To work around this error, we can specify `BucketOwnerPreferred` in cases where we use canned ACLs. Since our existing security posture already disallows public access, this is no different from the new and improved defaults.
> fix: adjust bucket ownership to allow ACLs (#12)

- s3.tf
As of terraform-aws-modules/terraform-aws-s3-bucket 3.9.0 the module now correctly accounts for the new default ACL settings. This commit reflects the latest guidance from the the module docs.
> fix(s3): set object ownership to ObjectWriter

- README.md
- subscription.tf
- variables.tf
Add a CloudWatch Logs subscription filter for the Observe Lambda's log group, by default, with the option to turn it off via `lambda_subscribe_logs = false`. 
This will send logs generated from the Lambda itself to Observe, aiding debugging issues with the Lambda's code.
Validates via `terraform validate`. We've also done E2E testing and see Lambda logs hitting Observe.
> feat(subscription): subscribe to Lambda logs by default

- .github/workflows/spec-tests.yaml
- README.md
- infrastructure/README.md
- infrastructure/backend.tf
- infrastructure/main.tf
- infrastructure/providers.tf
- infrastructure/versions.tf
Enabled the ability to run our [AWS spec tests](https://github.com/observeinc/aws-test-kitchen) with only the terraform repository.
Putting the tests as workflow dispatch and every Monday until we have confidence in their stability / utility
We should have tests
The spec tests run on the aws-test-kitchen repository successfully.
I've also ran these tests using a fork of the terraform-aws-collection repository
Example: https://github.com/observeinc/aws-test-kitchen/actions/runs/6151706105
> feat(spec-tests): introduce aws spec tests

- modules/config/README.md
- modules/config/iam.tf
Allow AWS Config to publish change notifications to a provided SNS topic.
We can not use `count` on `var.sns_topic_arn` to gate the construction of the IAM policy in this case. Terraform will complain it cannot determine the number of instances prior to apply. Instead we always declare a well formed policy, but only inline it if an SNS topic is provided.
> feat(config): allow publishing to SNS topic

- README.md
- lambda.tf
- variables.tf
Upgrade the lambda dependency to get the go1.x deprecation https://github.com/observeinc/terraform-aws-lambda/commit/8fd6b3f28bf5213e8ec83041448a4fab80162566
Wrote a spec job that fails when ran against terraform-aws-collection@main [failing spec test](https://github.com/observeinc/aws-test-kitchen/actions/runs/6750032095/job/18761797308#step:12:1597)
Ran the same spec test against this branch and it passes [passing spec test](https://github.com/observeinc/aws-test-kitchen/actions/runs/6896535494/job/18762858148#step:12:1625)
Also used `examples/simple` to install onto an AWS account
> chore(deps): bump observeinc/lambda/aws from 3.3.0 to 3.4.0

- README.md
- eventbridge.tf
- examples/simple/main.tf
- examples/simple/tests/simple.tftest.hcl
- examples/simple/versions.tf
- firehose.tf
- modules/config/README.md
- modules/config/versions.tf
- modules/forwarder/README.md
- modules/forwarder/versions.tf
- s3.tf
- subscription.tf
- versions.tf
Bump modules to latest versions. As a result of these upgrades, the minimum terraform AWS provider is now 5.0.
> feat: bump kinesis firehose, s3 modules

- modules/config/README.md
- modules/config/config.tf
- modules/config/main.tf
- modules/config/tests/config.tftest.hcl
- modules/config/variables.tf
- modules/config/versions.tf
This commit provides parity configuration wise with what is provided in our AWS SAM cloudformation templates.
> fix(config): add `include_resource_types` and `exclude_resource_types`

- README.md
- examples/simple/versions.tf
- modules/forwarder/README.md
- modules/forwarder/versions.tf
- versions.tf
For consistency across modules, pin the minimum terraform version to 1.2. This avoids issues in our current test actions where we detect the minimum version based on the root module, rather than computing the minimum based on the module being tested.
> fix: bump minimum terraform version to 1.2

- modules/logwriter/README.md
- modules/logwriter/iam.tf
- modules/logwriter/main.tf
- modules/logwriter/variables.tf
- modules/subscriber/README.md
- modules/subscriber/iam.tf
- modules/subscriber/main.tf
- modules/subscriber/scheduler.tf
- modules/subscriber/variables.tf
This commit fixes too small bugs:
- name_prefix must be under 38 characters. If we're provided a longer name, we should truncate the value instead of erroring out.
- discovery_rate was set to nullable, but passing null would result in an error when comparing the value against an empty string.
> fix(subscriber): adjust discovery_rate default and name_prefix

- modules/forwarder/README.md
- modules/forwarder/outputs.tf
- modules/logwriter/README.md
- modules/logwriter/iam.tf
- modules/logwriter/main.tf
- modules/logwriter/variables.tf
- modules/subscriber/README.md
- modules/subscriber/iam.tf
- modules/subscriber/main.tf
- modules/subscriber/scheduler.tf
- modules/subscriber/variables.tf
This is needed in order for other modules to trigger the forwarder by queuing tasks for the lambda to process.
> fix(forwarder): output queue ARN

- modules/logwriter/tests/logwriter.tftest.hcl
- modules/metricstream/tests/metricstream.tftest.hcl
- modules/testing/s3_bucket/kms.tf
- modules/testing/s3_bucket/main.tf
- modules/testing/s3_bucket/outputs.tf
- modules/testing/s3_bucket/variables.tf
Add the ability to encrypt S3 bucket using a KMS key to our testing setup module. This will allow us to verify that we can grant the forwarder lambda permissions to decrypt data given a KMS key.
> feat(testing): encrypt S3 bucket using KMS

- modules/logwriter/README.md
- modules/logwriter/subscriber.tf
- modules/logwriter/tests/logwriter.tftest.hcl
- modules/logwriter/variables.tf
- modules/subscriber/README.md
- modules/subscriber/lambda.tf
- modules/subscriber/variables.tf
Adds new optional parameter `debug_endpoint` that when set starts emitting debugging telemetry data.
Optional - delete this section if it's already obvious
Optional - delete this section if it's not necessary
Required - let us know what you've done for testing so far. It helps the 
reviewer consider what more can be done to build confidence in the safety 
of the change.
> feat: add debug_endpoint param for OTEL debugging

- examples/forwarder-kms/README.md
- examples/forwarder-kms/main.tf
- examples/forwarder-kms/outputs.tf
- examples/forwarder-kms/tests/example.tftest.hcl
- examples/forwarder-kms/versions.tf
- modules/testing/observe_mock/README.md
- modules/testing/observe_mock/observe.tfmock.hcl
Add an example module that demonstrates reading files from KMS encrypted bucket. We introduce a mock provider in order to avoid needing Observe credentials to run tests.
> docs: add KMS forwarding example

- modules/forwarder/eventbridge.tf
We don't need this rule to have a known name, and we were providing a prefix.
> fix(forwarder): set name_prefix for eventbridge rule

- README.md
- lambda.tf
- s3.tf
- variables.tf
This can be useful for the case where we want to subscribe our collection bucket to multiple downstream consumers.
> feat: allow subscribing S3 bucket notifications to eventbridge

- README.md
- lambda.tf
- s3.tf
CS-425 update default aws snapshot lambda to 2gb and timeout to 120 seconds
Required - tell us about the great change you're submitting! It helps us know
what we need to review and how to collaborate on making it better.
Optional - delete this section if it's already obvious
Optional - delete this section if it's not necessary
Required - let us know what you've done for testing so far. It helps the 
reviewer consider what more can be done to build confidence in the safety 
of the change.
> fix: CS-425 update default aws snapshot lambda to 2gb and timeout 120s

- modules/forwarder/README.md
- modules/forwarder/variables.tf
The duration of `CopyObject` depends on file size and source and destination region. In order to account for large files, we need to increase our lambda timeout value.
> fix(forwarder): increase timeout

- modules/configsubscription/change.tf
- modules/configsubscription/oversized.tf
- modules/forwarder/queue.tf
Our targets were all referencing the same rule, and were additionally not able to write to SQS due to stringent permissions on the forwarder queue. This commit fixes the target references, and additionally relaxes forwarder policy to match what we do in our CloudFormation template.
> fix(configsubscription): match targets, relax permissions

- modules/forwarder/README.md
- modules/forwarder/lambda.tf
- modules/forwarder/main.tf
- modules/forwarder/queue.tf
- modules/forwarder/variables.tf
Memory usage will vary according to whether we are using filedrop or sending to HTTP. When sending to HTTP, memory and CPU usage will scale according to the size of input, whereas in Filedrop the object copy is essentially scale invariant. We should adjust our defaults accordingly rather than setting them in variables.
> fix(forwarder): adjust defaults based on URI

- .github/workflows/update-deps.yaml
- Makefile
- modules/metricstream/README.md
- modules/metricstream/cloudwatch.tf
- modules/metricstream/filters/recommended.yaml
- modules/metricstream/main.tf
- modules/metricstream/tests/metricstream.tftest.hcl
- modules/metricstream/variables.tf
- utilities/update-filters.sh
Previously we were collecting all metrics by omission. This commit instead loads a recommended set of filters from a file on disk. The file is kept in sync with the filter we provide for cloudformation.
We could have loaded the filter dynamically directly from the hosted URL, but that would be at odds with the idempotent nature of terraform modules. Since we already have to update the binary versions of lambda functions, we can piggyback on that process to mirror the file.
> fix(metricstream): set recommended filter by omission

- modules/forwarder/README.md
- modules/forwarder/outputs.tf
- modules/logwriter/README.md
- modules/logwriter/outputs.tf
- modules/stack/README.md
- modules/stack/outputs.tf
Our `stack` module was not surfacing any of its constituent elements. While reviewing outputs, I made minor adjustments to forwarder and logwriter outputs in order to make documentation clearer.
> fix(stack): add outputs

- modules/forwarder/eventbridge.tf
- modules/forwarder/iam.tf
- modules/forwarder/main.tf
The IAM role of the forwarder only needs to be known when forwarding data to Filedrop. For cases where we are not pointing at an S3 data access point, we can fallback to provisioning a role with `name_prefix` rather than `name`. Doing so avoids the possibility of name clashes when installing a forwarder in different regions.
> fix(forwarder): relax IAM role naming

- modules/forwarder/eventbridge.tf
This is purely cosmetic, but currently the SQS message surfaces leading whitespace:
```
"body": "      {\"copy\": [{\"uri\": \"s3://observe-collection-us-west-2-yk6du6wk/S3ServerLogs/2024-05-30-22-20-38-55B93A2E2EA22E26\", \"size\": 3782}]}\n",
```
> fix(forwarder): strip leading whitespace in eventbridge rule

- modules/forwarder/tests/validation.tftest.hcl
- modules/forwarder/variables.tf
I wasted 20 minutes debugging what turned out to be a bad input variable to the forwarder module. This commit adds stricter validation.
> fix(forwarder): improve variable checks

- modules/logwriter/README.md
- modules/logwriter/variables.tf
- modules/stack/logwriter.tf
This behavior predates changes in the forwarder lambda which match on path under `AWSLogs/`.
> fix(logwriter): remove default prefix

- modules/subscriber/README.md
- modules/subscriber/eventbridge.tf
This commit adds an eventbridge rule to trigger the subscriber lambda on log group creation. This functionality was missing from terraform, but correctly implemented in cloudformation.
> fix(logwriter): subscribe on log group creation

- modules/forwarder/eventbridge.tf
Terraform counterpart to https://github.com/observeinc/aws-sam-apps/pull/307
> fix(forwarder): filter eventbridge triggers by source bucket

- modules/forwarder/tests/validation.tftest.hcl
- modules/forwarder/variables.tf
Verify variable is a valid bucket name, if provided.
> fix(forwarder): validate destination bucket name

- modules/externalrole/README.md
- modules/externalrole/main.tf
- modules/externalrole/outputs.tf
- modules/externalrole/tests/externalrole.tftest.hcl
- modules/externalrole/variables.tf
- modules/externalrole/versions.tf
Add module which streamlines creation of an IAM role that can be assumed by external entity. This is necessary for streamlining onboarding of pollers.
> feat: add externalrole module

- modules/externalrole/README.md
- modules/externalrole/outputs.tf
Returning an `arn` rather than a `role` reduces the stuttering when referring to the `externalrole` module, e.g: `module.metrics_role.arn` vs `module.metrics_role.role.arn`.
> fix(externalrole): adjust outputs.

- .gitignore
- README.md
- examples/forwarder-kms/README.md
- examples/forwarder-kms/main.tf
- examples/stack-filedrop/README.md
- examples/stack-filedrop/main.tf
- main.tf
- modules/config/README.md
- modules/config/iam.tf
- modules/config/main.tf
- modules/externalrole/README.md
- modules/externalrole/main.tf
- modules/forwarder/iam.tf
- modules/forwarder/queue.tf
- s3.tf
Update to use [aws_partition](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/partition) to retrieve AWS partition to deploy to China, which can have a value `aws` or  `aws-cn`.
> feat: Update to use aws_partition for AWS China (aws-cn) compatibility

- .github/workflows/tests-integration.yaml
Updating tests to install Terraform on ubuntu as ubuntu-latest no longer includes Terraform. 
Pull requests have been failing due to Terraform missing on Ubuntu image:
```
terraform -chdir=./examples/forwarder-sns init -upgrade
make: terraform: No such file or directory
make: *** [Makefile:4: test-dir] Error 127
Error: Process completed with exit code 2.
```
See also https://github.com/actions/runner-images/issues/10796
> chore: Update tests to install Terraform on Ubuntu image

- modules/stack/s3.tf
Addresses a warning emitted by the Terraform AWS Provider for the `aws_s3_bucket_lifecycle_configuration` module:
```
│ Warning: Invalid Attribute Combination
│
│   with module.observe.aws_s3_bucket_lifecycle_configuration.this,
│   on .terraform/modules/observe/modules/stack/s3.tf line 15, in resource "aws_s3_bucket_lifecycle_configuration" "this":
│   15: resource "aws_s3_bucket_lifecycle_configuration" "this" {
│
│ No attribute specified when one (and only one) of [rule[0].filter,rule[0].prefix] is required
│
│ This will be an error in a future version of the provider
```
Validated that the example stack applies and functions as expected without warnings.
> feat: Add filter and prefix to S3 aws_s3_bucket_lifecycle_configuration - OB-44161

- README.md
- subscription.tf
Update `cloudwatch-logs-subscription` version to v0.6.0 to move from Python3.9 to Python3.13. Python 3.9 will be deprecated 12/15/2025.
> feat: Update cloudwatch-logs-subscription to v0.6.0
